### PR TITLE
fix build on Dune 2.3

### LINKED ISSUE #75: OPM build failed: ecfvstencil.hh:250:58: error: ‘ePtr’ was not declared
```
          ^
Linking CXX executable bin/art2dgf
[  0%] Built target art2dgf
Scanning dependencies of target co2injection_flash_ecfv
[  1%] Building CXX object CMakeFiles/co2injection_flash_ecfv.dir/tests/co2injection_flash_ecfv.cc.o
In file included from <https://ci.statoil.no/job/OPM7/ws/ewoms/ewoms/disc/ecfv/ecfvdiscretization.hh>:34:0,
                 from <https://ci.statoil.no/job/OPM7/ws/ewoms/tests/co2injection_flash_ecfv.cc>:37:
<https://ci.statoil.no/job/OPM7/ws/ewoms/ewoms/disc/ecfv/ecfvstencil.hh>: In member function ‘void Ewoms::EcfvStencil<Scalar, GridView>::updateTopology(const Element&)’:
<https://ci.statoil.no/job/OPM7/ws/ewoms/ewoms/disc/ecfv/ecfvstencil.hh>:250:58: error: ‘ePtr’ was not declared in this scope
         subControlVolumes_.emplace_back(SubControlVolume(ePtr));
                                                          ^
<https://ci.statoil.no/job/OPM7/ws/ewoms/ewoms/disc/ecfv/ecfvstencil.hh>: In member function ‘void Ewoms::EcfvStencil<Scalar, GridView>::updatePrimaryTopology(const Element&)’:
<https://ci.statoil.no/job/OPM7/ws/ewoms/ewoms/disc/ecfv/ecfvstencil.hh>:285:58: error: ‘ePtr’ was not declared in this scope
         subControlVolumes_.emplace_back(SubControlVolume(ePtr));
                                                          ^
make[2]: *** [CMakeFiles/co2injection_flash_ecfv.dir/tests/co2injection_flash_ecfv.cc.o] Error 1
make[1]: *** [CMakeFiles/co2injection_flash_ecfv.dir/all] Error 2
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
[WARNINGS] Skipping publisher since build result is FAILURE
```

### PR DESCRIPTION
**Pull request by andlaus**
that broke because of a silly mistake I made yesterday and I did not
test it with Dune 2.3. (maybe Dune 2.3 support should be dropped soon
anyway...)

this should fix #75. once the CI systems are green, I'll thus self-merge.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> maybe Dune 2.3 support should be dropped soon
> anyway

For the 2017.04 release we'll have to support 2.5, so it would be good to drop 2.3. However we may have users needing to stay on 2.3. I suggest we pose that question to the mailing list after the release is done.

**Comment by pgdr** [comment]
Close the issue at will.

**Comment by andlaus** [comment]
> I suggest we pose that question to the mailing list after the release is done.

+1. We should probably also query if somebody needs support for GCC < 4.9 (i.e., a GCC which does not support c++-2011 fully). That should allow us to drop `FindCXXFeatures.cmake` and the `boost::regex` dependency. opinions, @akva2?

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
The Travis check should, I think, be sufficient to verify that this is ok and can be merged, otherwise what is checked by the jenkins run so that we must wait for it?

**Comment by andlaus** [comment]
> The Travis check should, I think, be sufficient to verify that this is ok and can be merged, otherwise what is checked by the jenkins run so that we must wait for it?

true. jenkins compiled a few tests, so it should also be happy when it is finished. merging,

**Comment by blattms** [comment]
The current Debian stable ships 2.3 and it is really handy being able
to use these packages. Of course people could use the backported 2.4
packages. I would suggest to leave it as is for the current release
and drop 2.3 afterwards. 

The next version  will most probably be using
DUNE 2.5, but that will not be released before spring 2017. BTW I am
currently testing with DUNE 2.5 and will provide patches if needed.

**Comment by akva2** [comment]
if we are to drop gcc 4.8 support, we have to drop ubuntu trusty / use an non-standard toolchain as that is based on 4.8.5. we would also need to use an additional toolset on rhel7, as that is also on 4.8.5. rhel6 would be fine, as we already use gcc 4.9 there. so to me, it sounds a bit early.

**Comment by andlaus** [comment]
ok. seems like the older versions will stick around for a while...
